# Nomor 2 - Latihan Responsi AHP

Studi Kasus: Pemilihan pembelian motor.

Nama: Gusti Rama

NIM: 123230040

Plug: IF-F

## Pengaturan Data

Penentuan **Alternatif** dan **Kriteria**
- Alternatif
    - A1: Canon EOS R6
    - A2: Nikon Z6 II
    - A3: Sony Alpha A7 III
    - A4: Fujifilm X-T4
    - A5: Panasonic Lumix GH5
- Kriteria
    - C1: RAM
    - C2: Harga
    - C3: Kamera
    - C4: Baterai
    - C5: Storage

**Spesifikasi**:
|  |Resolusi (MP) | Harga (rp) | Baterai | Video (fps) | Berat (gr) |
|------------|------------|------------|------------|------------|------------|
| A1 | 20 | 42.000.000 | 510 | 60 | 680 |
| A2 | 24 | 38.000.000 | 360 | 120 | 705 |
| A3 | 24 | 39.500.000 | 610 | 60 | 650 |
| A4 | 26 | 29.000.000 | 500 | 60 | 607 |
| A5 | 20 | 21.000.000 | 400 | 60 | 725 |

**Tingkat Kepentingan**:
| Intensitas | Keterangan |
|------------|------------|
| 1 | X dan Y sama penting/baik |
| 2 | X sedikit lebih penting/baik dari Y |
| 3 | X lebih penting/baik dari Y |
| 4 | X jauh lebih penting/baik dari Y |

**Preferensi Kriteria**
1. Resolusi 4 kali lebih penting dari Berat, 3 kali lebih penting dari Harga, dan 4 kali
lebih penting dari Baterai.
2. Harga 3 kali lebih penting dari Baterai dan 2 kali lebih penting dari Fitur Video.
3. Baterai 2 kali lebih penting dari Fitur Video dan 2 kali lebih penting dari Berat.
4. Fitur Video 2 kali lebih penting dari Berat.
5. Berat merupakan kriteria dengan prioritas paling rendah.

In [19]:
import numpy as np

In [20]:
def hitung_normalisasi(M):
    print("\n Normalisasi")
    if M.ndim == 1:
        sM = np.sum(M)
        return M/sM
    else:
      sM = np.sum(M, axis = 0)
      return M/sM

In [21]:
# R = Resolusi H= Harga Btr = Baterai V= Video Bt = Berat
MPBK = np.array([ 
  #R   H   Btr   V    Br
[1/1, 3/1, 4/1, 2/1, 4/1], # R
[1/3, 1/1, 3/1, 2/1, 4/1], # H
[1/4, 1/3, 1/1, 2/1, 2/1], # Btr
[1/2, 1/2, 1/2, 1/1, 2/1], # V
[1/4, 1/4, 2/1, 1/2 ,1/1]  # Br
])
print(MPBK)

[[1.         3.         4.         2.         4.        ]
 [0.33333333 1.         3.         2.         4.        ]
 [0.25       0.33333333 1.         2.         2.        ]
 [0.5        0.5        0.5        1.         2.        ]
 [0.25       0.25       2.         0.5        1.        ]]


In [22]:
w_MPBK = hitung_normalisasi(MPBK)
print(w_MPBK)


 Normalisasi
[[0.42857143 0.59016393 0.38095238 0.26666667 0.30769231]
 [0.14285714 0.19672131 0.28571429 0.26666667 0.30769231]
 [0.10714286 0.06557377 0.0952381  0.26666667 0.15384615]
 [0.21428571 0.09836066 0.04761905 0.13333333 0.15384615]
 [0.10714286 0.04918033 0.19047619 0.06666667 0.07692308]]


In [23]:
m, n = w_MPBK.shape
V = np.zeros(m)
for i in range(m):
    V[i] = np.sum(w_MPBK[i,:])
    
w_MPBK = V / m
print(w_MPBK)

[0.39480934 0.23993034 0.13769351 0.12948898 0.09807782]


# STEP 1 : Resolusi

In [24]:
# RESOLUSI
A1= 20 
A2= 24 
A3= 24 
A4= 26 
A5= 20 

m_R= np.array([A1,A2,A3,A4,A5])

In [25]:
w_R = hitung_normalisasi(m_R)
print(w_R)


 Normalisasi
[0.1754386  0.21052632 0.21052632 0.22807018 0.1754386 ]


# Step 2 : Harga


In [26]:
# Harga
A1= 42000000 
A2= 38000000 
A3= 39000000  
A4= 29000000  
A5= 21000000  

m_H= np.array([A1,A2,A3,A4,A5])

In [27]:
w_H = hitung_normalisasi(m_H)
print(w_H)


 Normalisasi
[0.24852071 0.22485207 0.23076923 0.17159763 0.12426036]


# Step 3 : Baterai

In [28]:
A1= 510 
A2= 360
A3= 610 
A4= 500
A5= 400
m_B= np.array([A1,A2,A3,A4,A5])

In [29]:
w_B = hitung_normalisasi(m_B)
print(w_B)


 Normalisasi
[0.21428571 0.1512605  0.25630252 0.21008403 0.16806723]


# Step 4 : Video

In [30]:
A1= 60
A2= 120
A3= 60 
A4= 60
A5= 60
m_V= np.array([A1,A2,A3,A4,A5])

In [31]:
w_V = hitung_normalisasi(m_V)
print(w_V)


 Normalisasi
[0.16666667 0.33333333 0.16666667 0.16666667 0.16666667]


# Step 5 : Berat

In [32]:
A1= 680
A2= 705
A3= 650
A4= 607
A5= 725
m_Br= np.array([A1,A2,A3,A4,A5])

In [33]:
w_Br = hitung_normalisasi(m_Br)
print(w_Br)


 Normalisasi
[0.2019602  0.20938521 0.19305019 0.18027918 0.21532522]


# FINISHING

In [34]:
wM = np.column_stack((w_R, w_H, w_B, w_V, w_Br))
print(wM)

[[0.1754386  0.24852071 0.21428571 0.16666667 0.2019602 ]
 [0.21052632 0.22485207 0.1512605  0.33333333 0.20938521]
 [0.21052632 0.23076923 0.25630252 0.16666667 0.19305019]
 [0.22807018 0.17159763 0.21008403 0.16666667 0.18027918]
 [0.1754386  0.12426036 0.16806723 0.16666667 0.21532522]]


In [35]:
mC_Scores = np.dot(wM, w_MPBK)
print(mC_Scores)

[0.19978752 0.22159322 0.21429293 0.19940581 0.16492052]
